spring:
  application:
    name: PRODUCT-SERVICE

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/microService_db
    username: root
    password: computer
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

  config:
    import: configserver:http://localhost:9296  # Ensuring this is correctly placed

server:
  port: 8585




#eureka:
#  instance:
#    prefer-ip-address: true
#    hostname: localhost
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#  serviceUrl:
#    defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
